### ISSUE TITLE
Github page is broken

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/styleguide#5]
See: http://ombulabs.github.io/styleguide/

**Comment by schmierkov** [comment]
@cecilia-ombulabs seems the path change was not right, I wonder why this is broken in development then 😱

**Comment by cecilia-ombulabs** [comment]
@etagwerker @schmierkov 
It's working now. But we still need to deploy the styleguide in ombulabs.com, so it can work in production!

**Comment by etagwerker** [comment]
@cecilia-ombulabs @schmierkov Great! I see that http://ombulabs.github.io/styleguide/ is back to normal.
